/*   CRTCMD CMD(APLLIB/OTODFT)    +
            PGM(*LIBL/OTODFTB1)   +
            SRCFILE(APLLIB/QSRC)  +
            SRCMBR(OTODFTM1)      +
            REPLACE(*YES)         */
CMD  PROMPT('Get Default Output Options') ALLOW(*IPGM *BPGM)

PARM OTO     *CHAR 4096              PROMPT('VAR FOR OUTPUT STRING') RTNVAL(*YES)
PARM OUTMOD  *CHAR   2  MIN(1)       PROMPT('MODULE')
PARM PGMNME  *CHAR  10  MIN(1)       PROMPT('PROGRAM')
PARM PRTFLE  *CHAR  10  DFT(QPRINT)  PROMPT('PRINT FILE')
PARM PGEWID  *CHAR   3  DFT(132)     PROMPT('PAGE WIDTH')
PARM PGELEN  *CHAR   3  DFT(66)      PROMPT('PAGE LENGTH')
PARM PRTOUT  *CHAR   1  DFT(Y)       PROMPT('PRINT OUTPUT')
PARM EMLOUT  *CHAR   1  DFT(N)       PROMPT('EMAIL OUTPUT')
PARM ARCOUT  *CHAR   1  DFT(N)       PROMPT('ARCHIVE OUTPUT')
PARM FAFOUT  *CHAR   1  DFT(N)       PROMPT('FAX OUTPUT')

PARM PSTFLG  *CHAR   1  DFT(N)       PROMPT('OUTPUT IS A POSTING')

PARM PRTDEV  *CHAR  10  DFT(*USRPRF) PROMPT('PRINTER DEV')  EXPR(*YES)
PARM PRTOTQ  *CHAR  10  DFT(*DEV)    PROMPT('OUTPUT QUEUE') EXPR(*YES)
PARM HLDOUT  *CHAR   5  DFT(*NO)     PROMPT('HOLD OUTPUT')
PARM SAVOUT  *CHAR   5  DFT(*NO)     PROMPT('SAVE OUTPUT')
PARM PRTFRM  *CHAR  10  DFT(*STD)    PROMPT('FORM')         EXPR(*YES)
PARM USRDTA  *CHAR  10  DFT(*SAME)   PROMPT('USER DATA')    EXPR(*YES)
PARM NBRCPY  *CHAR   3  DFT(001)     PROMPT('COPY')
PARM PRTQUL  *CHAR  10  DFT(*SAME)   PROMPT('PRINT QUALITY') EXPR(*YES)
PARM PRTOVL  *CHAR  10  DFT(*NONE)   PROMPT('FAX COVER OVERLAY') EXPR(*YES)

PARM ARCFLR  *CHAR 128  DFT('')      PROMPT('ARCHIVE FOLDER') EXPR(*YES)
PARM AARFLR  *CHAR 128  DFT('')      PROMPT('AUTO ARCHIEVE FOLDER') EXPR(*YES)

PARM FAXNBR  *CHAR  20  DFT(1)       PROMPT('FAX NUMBER') EXPR(*YES)

PARM EMLADD  *CHAR  60  DFT('')      PROMPT('TO EMAIL ADD.') EXPR(*YES)
PARM EMLNME  *CHAR  60  DFT('')      PROMPT('TO NAME') EXPR(*YES)
PARM FRMEML  *CHAR  30  DFT('')      PROMPT('FROM ADDRESS') EXPR(*YES)
PARM FRMNME  *CHAR  30  DFT('')      PROMPT('FROM NAME') EXPR(*YES)
PARM CC1EML  *CHAR  60  DFT('')      PROMPT('CC ADDRESS 1') EXPR(*YES)
PARM CC1NME  *CHAR  30  DFT('')      PROMPT('CC NAME 1') EXPR(*YES)
PARM CC2EML  *CHAR  60  DFT('')      PROMPT('CC ADDRESS 2') EXPR(*YES)
PARM CC2NME  *CHAR  30  DFT('')      PROMPT('CC NAME 2') EXPR(*YES)
PARM CC3EML  *CHAR  60  DFT('')      PROMPT('CC ADDRESS 3') EXPR(*YES)
PARM CC3NME  *CHAR  30  DFT('')      PROMPT('CC NAME 3') EXPR(*YES)
PARM BCCEML  *CHAR  60  DFT('')      PROMPT('BCC ADDRESS') EXPR(*YES)
PARM BCCNME  *CHAR  30  DFT('')      PROMPT('BCC NAME') EXPR(*YES)
PARM EMLSBJ  *CHAR  60  DFT('')      PROMPT('SUBJECT') EXPR(*YES)

PARM ATATYP  *CHAR   5  DFT(*PDF)    PROMPT('EMAIL ATTACHMENT TYPE')
PARM VLDATA  *CHAR   1  RSTD(*YES)   PROMPT('VALID ATTACHMENT TYPES') +
                  VALUES(1 2 3 4 ' ') +
                  CHOICE('=PDF;2=+CSV,3=+XML,4=+XLS')
PARM ATANME  *CHAR 128   DFT('')     PROMPT('FILE NAME') CASE(*MIXED) EXPR(*YES)
PARM ATAFMT  *CHAR   1   RSTD(*YES)  PROMPT('EMAIL CSV FORMAT') +
          DFT(1)  VALUES(1 2)     CHOICE('1=DATA,2=REPORT')
PARM CRTXMA  *CHAR   1   DFT(*PDF)   PROMPT('XML ATTRIBUTE FILE')

PARM MSG01   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 1') EXPR(*YES)
PARM MSG02   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 2') EXPR(*YES)
PARM MSG03   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 3') EXPR(*YES)
PARM MSG04   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 4') EXPR(*YES)
PARM MSG05   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 5') EXPR(*YES)
PARM MSG06   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 6') EXPR(*YES)
PARM MSG07   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 7') EXPR(*YES)
PARM MSG08   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 8') EXPR(*YES)
PARM MSG09   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 9') EXPR(*YES)
PARM MSG10   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 10') EXPR(*YES)
PARM MSG11   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 11') EXPR(*YES)
PARM MSG12   *CHAR  75   DFT('')     PROMPT('MESSAGE LINE 12') EXPR(*YES)
